version: '3.4'
services:
  bot-dgg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-dgg
    user: 1004:1004
    volumes:
      - ./prod.config.json:/usr/src/app/lib/configuration/prod.config.json:ro
      - ./database:/usr/src/app/database
    command: ["node", "/usr/src/app/index.js"]
    restart: unless-stopped
    network_mode: "host"
    environment:
      - NODE_ENV=production